//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionTemp
    {
        public int IdUser { get; set; }
        public string ComputerName { get; set; }
        public string ComputerMacAddress { get; set; }
        public string ComputerUserName { get; set; }
        public System.DateTime ConnexionDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
