//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordKeeper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PasswordKeeperEntities : DbContext
    {
        public PasswordKeeperEntities()
            : base("name=PasswordKeeperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CustomField> CustomFields { get; set; }
        public virtual DbSet<ConnectionTemp> ConnectionTemps { get; set; }
    }
}
